# Generated by Django 4.2.9 on 2024-01-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leg",
            options={"ordering": ["cruise", "leg_number"]},
        ),
        migrations.RenameField(
            model_name="leg",
            old_name="leg",
            new_name="leg_number",
        ),
        migrations.CreateModel(
            name="Dredge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dredge_number", models.CharField(max_length=100)),
                (
                    "leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dredges", to="rocks.leg"
                    ),
                ),
            ],
            options={
                "ordering": ["leg", "dredge_number"],
            },
        ),
    ]
