# Generated by Django 4.2.9 on 2024-01-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0002_alter_leg_options_rename_leg_leg_leg_number_dredge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sample_number", models.CharField(max_length=100)),
                ("sub_sample", models.CharField(blank=True, max_length=100)),
                ("primary_lithology", models.CharField(blank=True, max_length=100)),
                ("av_grain_size", models.CharField(blank=True, max_length=100)),
                ("texture", models.CharField(blank=True, max_length=100)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("glass", models.CharField(blank=True, max_length=100)),
                ("pelag", models.CharField(blank=True, max_length=100)),
                ("comments", models.CharField(blank=True, max_length=100)),
                ("sampled_by", models.CharField(blank=True, max_length=100)),
                (
                    "dredge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="samples", to="rocks.dredge"
                    ),
                ),
            ],
            options={
                "ordering": ["dredge", "sample_number"],
            },
        ),
    ]
