# Generated by Django 4.2.9 on 2024-01-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0003_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamplePhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="data_files")),
                (
                    "dredge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sample_photos", to="rocks.dredge"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="rocks.samplephoto",
            ),
        ),
    ]
