# Generated by Django 4.2.9 on 2024-01-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0004_samplephoto_sample_sample_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplephoto",
            name="file",
            field=models.ImageField(upload_to="sample_photos"),
        ),
    ]
