# Generated by Django 4.2.9 on 2024-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0005_alter_samplephoto_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dredge",
            name="description_file",
            field=models.FileField(blank=True, null=True, upload_to="description_files"),
        ),
    ]
