# Generated by Django 4.2.9 on 2024-01-24 15:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0006_dredge_description_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplephoto",
            name="file",
            field=sorl.thumbnail.fields.ImageField(upload_to="sample_photos"),
        ),
    ]
