# Generated by Django 4.2.9 on 2024-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0007_alter_samplephoto_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplephoto",
            name="file",
            field=models.ImageField(upload_to="sample_photos"),
        ),
    ]
