# Generated by Django 4.2.9 on 2024-01-24 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0009_alter_samplephoto_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="pelag",
            new_name="palag",
        ),
    ]
