# Generated by Django 4.2.9 on 2024-03-25 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rocks", "0013_sample_sample_photomicrograph"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="contact",
            new_name="weight",
        ),
    ]
