version: '3'

volumes:
  dredge_core_rocks_local_postgres_data: {}
  dredge_core_rocks_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dredge_core_rocks_local_django
    container_name: dredge_core_rocks_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dredge_core_rocks_production_postgres
    container_name: dredge_core_rocks_local_postgres
    volumes:
      - dredge_core_rocks_local_postgres_data:/var/lib/postgresql/data
      - dredge_core_rocks_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6.2
    restart: unless-stopped
